#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from jqdatasdk import valuation, indicator, balance, income, cash_flow

#涨跌幅

VALUATION_INDICATOR_MAPPING = dict.fromkeys(['capitalization'], valuation.capitalization)
VALUATION_INDICATOR_MAPPING.update(dict.fromkeys(['circulating_cap'], valuation.circulating_cap))
VALUATION_INDICATOR_MAPPING.update(dict.fromkeys(['market_cap'], valuation.market_cap))
VALUATION_INDICATOR_MAPPING.update(dict.fromkeys(['circulating_market_cap'], valuation.circulating_market_cap))
VALUATION_INDICATOR_MAPPING.update(dict.fromkeys(['turnover_ratio'], valuation.turnover_ratio))
VALUATION_INDICATOR_MAPPING.update(dict.fromkeys(['pe_ratio'], valuation.pe_ratio))
VALUATION_INDICATOR_MAPPING.update(dict.fromkeys(['pe_ratio_lyr'], valuation.pe_ratio_lyr))
VALUATION_INDICATOR_MAPPING.update(dict.fromkeys(['pb_ratio'], valuation.pb_ratio))
VALUATION_INDICATOR_MAPPING.update(dict.fromkeys(['ps_ratio'], valuation.ps_ratio))
VALUATION_INDICATOR_MAPPING.update(dict.fromkeys(['pcf_ratio'], valuation.pcf_ratio))


RATIO_INDICATOR_MAPPING = dict.fromkeys(['eps'], indicator.eps)
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['adjusted_profit'], indicator.adjusted_profit))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['operating_profit'], indicator.operating_profit))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['value_change_profit'], indicator.value_change_profit))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['roe'], indicator.roe))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['inc_return'], indicator.inc_return))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['roa'], indicator.roa))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['net_profit_margin'], indicator.net_profit_margin))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['gross_profit_margin'], indicator.gross_profit_margin))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['expense_to_total_revenue'], indicator.expense_to_total_revenue))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['operation_profit_to_total_revenue'], indicator.operation_profit_to_total_revenue))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['net_profit_to_total_revenue'], indicator.net_profit_to_total_revenue))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['operating_expense_to_total_revenue'], indicator.operating_expense_to_total_revenue))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['ga_expense_to_total_revenue'], indicator.ga_expense_to_total_revenue))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['financing_expense_to_total_revenue'], indicator.financing_expense_to_total_revenue))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['operating_profit_to_profit'], indicator.operating_profit_to_profit))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['invesment_profit_to_profit'], indicator.invesment_profit_to_profit))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['adjusted_profit_to_profit'], indicator.adjusted_profit_to_profit))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['goods_sale_and_service_to_revenue'], indicator.goods_sale_and_service_to_revenue))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['ocf_to_revenue'], indicator.ocf_to_revenue))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['ocf_to_operating_profit'], indicator.ocf_to_operating_profit))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['inc_total_revenue_year_on_year'], indicator.inc_total_revenue_year_on_year))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['inc_total_revenue_annual'], indicator.inc_total_revenue_annual))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['inc_revenue_year_on_year'], indicator.inc_revenue_year_on_year))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['inc_revenue_annual'], indicator.inc_revenue_annual))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['inc_operation_profit_year_on_year'], indicator.inc_operation_profit_year_on_year))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['inc_operation_profit_annual'], indicator.inc_operation_profit_annual))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['inc_net_profit_year_on_year'], indicator.inc_net_profit_year_on_year))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['inc_net_profit_annual'], indicator.inc_net_profit_annual))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['inc_net_profit_to_shareholders_year_on_year'], indicator.inc_net_profit_to_shareholders_year_on_year))
RATIO_INDICATOR_MAPPING.update(dict.fromkeys(['inc_net_profit_to_shareholders_annual'], indicator.inc_net_profit_to_shareholders_annual))



BALANCE_INDICATOR_MAPPING = dict.fromkeys(['cash_equivalents'], balance.cash_equivalents)
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['settlement_provi'], balance.settlement_provi))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['lend_capital'], balance.lend_capital))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['trading_assets'], balance.trading_assets))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['bill_receivable'], balance.bill_receivable))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['account_receivable'], balance.account_receivable))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['advance_payment'], balance.advance_payment))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['insurance_receivables'], balance.insurance_receivables))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['reinsurance_receivables'], balance.reinsurance_receivables))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['reinsurance_contract_reserves_receivable'], balance.reinsurance_contract_reserves_receivable))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['interest_receivable'], balance.interest_receivable))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['dividend_receivable'], balance.dividend_receivable))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['other_receivable'], balance.other_receivable))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['bought_sellback_assets'], balance.bought_sellback_assets))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['inventories'], balance.inventories))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['non_current_asset_in_one_year'], balance.non_current_asset_in_one_year))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['other_current_assets'], balance.other_current_assets))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['total_current_assets'], balance.total_current_assets))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['loan_and_advance'], balance.loan_and_advance))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['hold_for_sale_assets'], balance.hold_for_sale_assets))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['hold_to_maturity_investments'], balance.hold_to_maturity_investments))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['longterm_receivable_account'], balance.longterm_receivable_account))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['longterm_equity_invest'], balance.longterm_equity_invest))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['investment_property'], balance.investment_property))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['fixed_assets'], balance.fixed_assets))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['constru_in_process'], balance.constru_in_process))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['construction_materials'], balance.construction_materials))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['fixed_assets_liquidation'], balance.fixed_assets_liquidation))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['biological_assets'], balance.biological_assets))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['oil_gas_assets'], balance.oil_gas_assets))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['intangible_assets'], balance.intangible_assets))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['development_expenditure'], balance.development_expenditure))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['good_will'], balance.good_will))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['long_deferred_expense'], balance.long_deferred_expense))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['deferred_tax_assets'], balance.deferred_tax_assets))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['other_non_current_assets'], balance.other_non_current_assets))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['total_non_current_assets'], balance.total_non_current_assets))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['total_assets'], balance.total_assets))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['shortterm_loan'], balance.shortterm_loan))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['borrowing_from_centralbank'], balance.borrowing_from_centralbank))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['deposit_in_interbank'], balance.deposit_in_interbank))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['borrowing_capital'], balance.borrowing_capital))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['trading_liability'], balance.trading_liability))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['notes_payable'], balance.notes_payable))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['accounts_payable'], balance.accounts_payable))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['advance_peceipts'], balance.advance_peceipts))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['sold_buyback_secu_proceeds'], balance.sold_buyback_secu_proceeds))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['commission_payable'], balance.commission_payable))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['salaries_payable'], balance.salaries_payable))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['taxs_payable'], balance.taxs_payable))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['interest_payable'], balance.interest_payable))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['dividend_payable'], balance.dividend_payable))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['other_payable'], balance.other_payable))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['reinsurance_payables'], balance.reinsurance_payables))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['insurance_contract_reserves'], balance.insurance_contract_reserves))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['proxy_secu_proceeds'], balance.proxy_secu_proceeds))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['receivings_from_vicariously_sold_securities'], balance.receivings_from_vicariously_sold_securities))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['non_current_liability_in_one_year'], balance.non_current_liability_in_one_year))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['other_current_liability'], balance.other_current_liability))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['total_current_liability'], balance.total_current_liability))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['longterm_loan'], balance.longterm_loan))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['bonds_payable'], balance.bonds_payable))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['longterm_account_payable'], balance.longterm_account_payable))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['specific_account_payable'], balance.specific_account_payable))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['estimate_liability'], balance.estimate_liability))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['deferred_tax_liability'], balance.deferred_tax_liability))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['other_non_current_liability'], balance.other_non_current_liability))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['total_non_current_liability'], balance.total_non_current_liability))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['total_liability'], balance.total_liability))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['paidin_capital'], balance.paidin_capital))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['capital_reserve_fund'], balance.capital_reserve_fund))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['treasury_stock'], balance.treasury_stock))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['specific_reserves'], balance.specific_reserves))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['surplus_reserve_fund'], balance.surplus_reserve_fund))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['ordinary_risk_reserve_fund'], balance.ordinary_risk_reserve_fund))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['retained_profit'], balance.retained_profit))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['foreign_currency_report_conv_diff'], balance.foreign_currency_report_conv_diff))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['equities_parent_company_owners'], balance.equities_parent_company_owners))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['minority_interests'], balance.minority_interests))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['total_owner_equities'], balance.total_owner_equities))
BALANCE_INDICATOR_MAPPING.update(dict.fromkeys(['total_sheet_owner_equities'], balance.total_sheet_owner_equities))



INCOME_INDICATOR_MAPPING = dict.fromkeys(['total_operating_revenue'], income.total_operating_revenue)
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['operating_revenue'], income.operating_revenue))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['interest_income'], income.interest_income))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['premiums_earned'], income.premiums_earned))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['commission_income'], income.commission_income))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['total_operating_cost'], income.total_operating_cost))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['operating_cost'], income.operating_cost))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['interest_expense'], income.interest_expense))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['commission_expense'], income.commission_expense))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['refunded_premiums'], income.refunded_premiums))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['net_pay_insurance_claims'], income.net_pay_insurance_claims))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['withdraw_insurance_contract_reserve'], income.withdraw_insurance_contract_reserve))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['policy_dividend_payout'], income.policy_dividend_payout))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['reinsurance_cost'], income.reinsurance_cost))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['operating_tax_surcharges'], income.operating_tax_surcharges))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['sale_expense'], income.sale_expense))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['administration_expense'], income.administration_expense))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['financial_expense'], income.financial_expense))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['asset_impairment_loss'], income.asset_impairment_loss))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['fair_value_variable_income'], income.fair_value_variable_income))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['investment_income'], income.investment_income))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['invest_income_associates'], income.invest_income_associates))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['exchange_income'], income.exchange_income))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['operating_profit'], income.operating_profit))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['non_operating_revenue'], income.non_operating_revenue))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['non_operating_expense'], income.non_operating_expense))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['disposal_loss_non_current_liability'], income.disposal_loss_non_current_liability))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['total_profit'], income.total_profit))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['income_tax_expense'], income.income_tax_expense))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['net_profit'], income.net_profit))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['np_parent_company_owners'], income.np_parent_company_owners))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['minority_profit'], income.minority_profit))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['basic_eps'], income.basic_eps))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['diluted_eps'], income.diluted_eps))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['other_composite_income'], income.other_composite_income))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['total_composite_income'], income.total_composite_income))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['ci_parent_company_owners'], income.ci_parent_company_owners))
INCOME_INDICATOR_MAPPING.update(dict.fromkeys(['ci_minority_owners'], income.ci_minority_owners))



CASHFLOW_INDICATOR_MAPPING = dict.fromkeys(['goods_sale_and_service_render_cash'], cash_flow.goods_sale_and_service_render_cash)
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['net_deposit_increase'], cash_flow.net_deposit_increase))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['net_borrowing_from_central_bank'], cash_flow.net_borrowing_from_central_bank))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['net_borrowing_from_finance_co'], cash_flow.net_borrowing_from_finance_co))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['net_original_insurance_cash'], cash_flow.net_original_insurance_cash))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['net_cash_received_from_reinsurance_business'], cash_flow.net_cash_received_from_reinsurance_business))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['net_insurer_deposit_investment'], cash_flow.net_insurer_deposit_investment))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['net_deal_trading_assets'], cash_flow.net_deal_trading_assets))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['interest_and_commission_cashin'], cash_flow.interest_and_commission_cashin))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['net_increase_in_placements'], cash_flow.net_increase_in_placements))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['net_buyback'], cash_flow.net_buyback))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['tax_levy_refund'], cash_flow.tax_levy_refund))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['other_cashin_related_operate'], cash_flow.other_cashin_related_operate))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['subtotal_operate_cash_inflow'], cash_flow.subtotal_operate_cash_inflow))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['goods_and_services_cash_paid'], cash_flow.goods_and_services_cash_paid))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['net_loan_and_advance_increase'], cash_flow.net_loan_and_advance_increase))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['net_deposit_in_cb_and_ib'], cash_flow.net_deposit_in_cb_and_ib))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['original_compensation_paid'], cash_flow.original_compensation_paid))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['handling_charges_and_commission'], cash_flow.handling_charges_and_commission))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['policy_dividend_cash_paid'], cash_flow.policy_dividend_cash_paid))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['staff_behalf_paid'], cash_flow.staff_behalf_paid))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['tax_payments'], cash_flow.tax_payments))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['other_operate_cash_paid'], cash_flow.other_operate_cash_paid))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['subtotal_operate_cash_outflow'], cash_flow.subtotal_operate_cash_outflow))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['net_operate_cash_flow'], cash_flow.net_operate_cash_flow))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['invest_withdrawal_cash'], cash_flow.invest_withdrawal_cash))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['invest_proceeds'], cash_flow.invest_proceeds))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['fix_intan_other_asset_dispo_cash'], cash_flow.fix_intan_other_asset_dispo_cash))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['net_cash_deal_subcompany'], cash_flow.net_cash_deal_subcompany))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['other_cash_from_invest_act'], cash_flow.other_cash_from_invest_act))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['subtotal_invest_cash_inflow'], cash_flow.subtotal_invest_cash_inflow))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['fix_intan_other_asset_acqui_cash'], cash_flow.fix_intan_other_asset_acqui_cash))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['invest_cash_paid'], cash_flow.invest_cash_paid))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['impawned_loan_net_increase'], cash_flow.impawned_loan_net_increase))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['net_cash_from_sub_company'], cash_flow.net_cash_from_sub_company))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['other_cash_to_invest_act'], cash_flow.other_cash_to_invest_act))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['subtotal_invest_cash_outflow'], cash_flow.subtotal_invest_cash_outflow))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['net_invest_cash_flow'], cash_flow.net_invest_cash_flow))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['cash_from_invest'], cash_flow.cash_from_invest))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['cash_from_mino_s_invest_sub'], cash_flow.cash_from_mino_s_invest_sub))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['cash_from_borrowing'], cash_flow.cash_from_borrowing))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['cash_from_bonds_issue'], cash_flow.cash_from_bonds_issue))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['other_finance_act_cash'], cash_flow.other_finance_act_cash))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['subtotal_finance_cash_inflow'], cash_flow.subtotal_finance_cash_inflow))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['borrowing_repayment'], cash_flow.borrowing_repayment))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['dividend_interest_payment'], cash_flow.dividend_interest_payment))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['proceeds_from_sub_to_mino_s'], cash_flow.proceeds_from_sub_to_mino_s))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['other_finance_act_payment'], cash_flow.other_finance_act_payment))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['subtotal_finance_cash_outflow'], cash_flow.subtotal_finance_cash_outflow))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['net_finance_cash_flow'], cash_flow.net_finance_cash_flow))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['exchange_rate_change_effect'], cash_flow.exchange_rate_change_effect))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['cash_equivalent_increase'], cash_flow.cash_equivalent_increase))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['cash_equivalents_at_beginning'], cash_flow.cash_equivalents_at_beginning))
CASHFLOW_INDICATOR_MAPPING.update(dict.fromkeys(['cash_and_equivalents_at_end'], cash_flow.cash_and_equivalents_at_end))


ALL_INDICATOR_MAPPING = {**VALUATION_INDICATOR_MAPPING, **RATIO_INDICATOR_MAPPING, **BALANCE_INDICATOR_MAPPING,**INCOME_INDICATOR_MAPPING,**CASHFLOW_INDICATOR_MAPPING}